update_fastlane

default_platform(:ios)

app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

app_store_connect_api_key_id = ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"]
app_store_connect_api_issuer_id = ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"]
app_store_connect_api_p8_contents = ENV["APP_STORE_CONNECT_API_KEY_KEY"]

platform :ios do
    
    # Tests
    desc "Run all the tests"
    lane :run_unit_tests do
        scan(
             scheme: "GitHub Insights",
             clean: true,
             devices: ["iPhone 15 Pro"],
             skip_detect_devices: true
             )
    end
    
    # Verifies and Updates Code Signing
    desc "match certificates"
    lane :match_certificates do
        match(type: "development",
              app_identifier: app_identifier
              )
              match(type: "appstore",
                    app_identifier: app_identifier
                    )
    end
    
    # Builds the App
    desc "Build the app"
    lane :build do
        gym(
            scheme: "GitHub Insights",
            clean: true,
            output_directory: "./fastlane/builds",
            output_name: "GitHub-Insights.ipa",
            include_bitcode: false,
            include_symbols: false
            )
    end
    
    # TestFlight upload
    desc "Uploads to TestFlight"
    lane :pilot_to_testflight do
        run_unit_tests
        match_certificates
        build
        api_key = app_store_connect_api_key(
            key_id: app_store_connect_api_key_id,
            issuer_id: app_store_connect_api_issuer_id,
            key_content: app_store_connect_api_p8_contents,
        )
                                            
        pilot(api_key: api_key)
    end
    
end
